-- Sends a file over rednet
write("Modem side: ")
local modemSide = read()
rednet.open(modemSide)
write("File to send: ")
local filename = read()
write("Send to: ")
local targetId = read()
local file = fs.open(filename, "r")
local contents = file.readAll()
file.close()
print("Sending "..filename.." to "..targetId)
rednet.send(targetId, contents)
print("file sent")